// Snapshot equivalence test: assert C++ JointMapper matches Python M4 baseline.
//
// Loads tests/fixtures/mapper_baseline.json (generated by scripts/dump_mapper_baseline.py)
// and re-runs the C++ JointMapper on the same example.json + config.yaml inputs.
// SHA-256 of inputs is embedded in the fixture and re-verified to catch silent drift.
//
// Built only when -DBUILD_TESTS=ON.

#include <array>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include <nlohmann/json.hpp>
#include <openssl/evp.h>          // EVP API — stable across OpenSSL 1.1.1 / 3.0+
                                  // (sha.h SHA256() is deprecated in OpenSSL 3.0)

#include "joint_mapper.hpp"
#include "udcap_receiver.hpp"

namespace {

constexpr double kEpsilonRad = 1e-6;

std::string read_text(const std::string& path) {
    std::ifstream f(path);
    if (!f) throw std::runtime_error("cannot open text file: " + path);
    std::stringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

std::vector<unsigned char> read_bytes(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) throw std::runtime_error("cannot open binary file: " + path);
    return std::vector<unsigned char>(std::istreambuf_iterator<char>(f),
                                       std::istreambuf_iterator<char>());
}

std::string sha256_hex(const std::vector<unsigned char>& bytes) {
    EVP_MD_CTX* ctx = EVP_MD_CTX_new();
    if (!ctx) throw std::runtime_error("EVP_MD_CTX_new failed");
    unsigned char hash[EVP_MAX_MD_SIZE];
    unsigned int hash_len = 0;
    bool ok =
        EVP_DigestInit_ex(ctx, EVP_sha256(), nullptr) == 1 &&
        EVP_DigestUpdate(ctx, bytes.data(), bytes.size()) == 1 &&
        EVP_DigestFinal_ex(ctx, hash, &hash_len) == 1;
    EVP_MD_CTX_free(ctx);
    if (!ok) throw std::runtime_error("EVP SHA-256 digest failed");

    std::ostringstream os;
    os << std::hex << std::setfill('0');
    for (unsigned int i = 0; i < hash_len; ++i) {
        os << std::setw(2) << static_cast<int>(hash[i]);
    }
    return os.str();
}

struct CliArgs {
    std::string fixture;
    std::string example;
    std::string config;
};

CliArgs parse_cli(int argc, char** argv) {
    CliArgs a;
    auto need_value = [&](int& i, const std::string& flag) {
        if (i + 1 >= argc) throw std::runtime_error(flag + " needs a value");
        return std::string(argv[++i]);
    };
    for (int i = 1; i < argc; ++i) {
        std::string f = argv[i];
        if      (f == "--fixture") a.fixture = need_value(i, f);
        else if (f == "--example") a.example = need_value(i, f);
        else if (f == "--config")  a.config  = need_value(i, f);
        else if (f == "--help" || f == "-h") {
            std::cout << "Usage: test_mapper_snapshot --fixture <path> --example <path> --config <path>\n";
            std::exit(0);
        } else {
            throw std::runtime_error("unknown flag: " + f);
        }
    }
    if (a.fixture.empty() || a.example.empty() || a.config.empty()) {
        throw std::runtime_error("required: --fixture <path> --example <path> --config <path>");
    }
    return a;
}

bool compare_hand(const char* tag,
                   const std::array<double, 12>& cpp,
                   const nlohmann::json& expected) {
    if (!expected.is_array() || expected.size() != 12) {
        std::cerr << "[ERROR] fixture '" << tag << "' must be an array of 12 floats\n";
        return false;
    }
    double max_diff = 0.0;
    int worst_j = -1;
    for (size_t i = 0; i < 12; ++i) {
        double e = expected.at(i).get<double>();
        double d = std::fabs(cpp[i] - e);
        if (d > max_diff) {
            max_diff = d;
            worst_j  = static_cast<int>(i);
        }
    }
    std::cout << "[INFO] " << tag << " joints max |Δ| = "
              << std::scientific << std::setprecision(1) << max_diff
              << " rad  (tol " << kEpsilonRad << ") → "
              << (max_diff <= kEpsilonRad ? "PASS" : "FAIL")
              << std::endl;
    if (max_diff > kEpsilonRad) {
        std::cerr << "[ERROR] " << tag << " joint " << worst_j
                  << " (" << JointMapper::kJointOrder[worst_j] << ") diff = "
                  << std::scientific << std::setprecision(3) << max_diff
                  << " exceeds tol " << kEpsilonRad << "\n"
                  << "[ERROR]   expected (python) = " << std::fixed << std::setprecision(9)
                  << expected.at(worst_j).get<double>() << "\n"
                  << "[ERROR]   actual   (cpp)    = " << cpp[worst_j] << "\n";
        return false;
    }
    return true;
}

}  // namespace

int main(int argc, char** argv) {
    CliArgs args;
    try { args = parse_cli(argc, argv); }
    catch (const std::exception& e) {
        std::cerr << "[ERROR] " << e.what() << std::endl;
        return 2;
    }

    // 1. Load fixture.
    nlohmann::json fix;
    try {
        std::ifstream f(args.fixture);
        if (!f) throw std::runtime_error("cannot open fixture: " + args.fixture);
        f >> fix;
    } catch (const std::exception& e) {
        std::cerr << "[ERROR] loading fixture: " << e.what() << "\n";
        return 1;
    }

    // 2. Verify SHA-256 of source files matches the fixture.
    try {
        std::string ex_sha  = sha256_hex(read_bytes(args.example));
        std::string cfg_sha = sha256_hex(read_bytes(args.config));
        auto fix_ex_sha  = fix.at("source").at("example_json_sha256").get<std::string>();
        auto fix_cfg_sha = fix.at("source").at("config_yaml_sha256").get<std::string>();
        if (fix_ex_sha != ex_sha) {
            std::cerr << "[ERROR] example.json SHA-256 mismatch\n"
                      << "[ERROR]   fixture: " << fix_ex_sha << "\n"
                      << "[ERROR]   actual : " << ex_sha << "\n"
                      << "[ERROR]   → regenerate via scripts/dump_mapper_baseline.py\n";
            return 1;
        }
        if (fix_cfg_sha != cfg_sha) {
            std::cerr << "[ERROR] config.yaml SHA-256 mismatch\n"
                      << "[ERROR]   fixture: " << fix_cfg_sha << "\n"
                      << "[ERROR]   actual : " << cfg_sha << "\n"
                      << "[ERROR]   → regenerate via scripts/dump_mapper_baseline.py\n";
            return 1;
        }
    } catch (const std::exception& e) {
        std::cerr << "[ERROR] SHA-256 check: " << e.what() << "\n";
        return 1;
    }
    std::cout << "[INFO] fixture SHA-256 match: example.json + config.yaml unchanged\n";

    // 3. Parse example.json into UdcapFrame using the same path as the receiver.
    auto frame = parse_udcap_payload(read_text(args.example));
    if (!frame) {
        std::cerr << "[ERROR] failed to parse example.json into UdcapFrame\n";
        return 1;
    }

    // 4. Run C++ mapper, compare to fixture.
    std::cout << "[INFO] running JointMapper on example.json\n";
    JointMapper mapper(args.config);
    auto cpp_left  = mapper.map_left(frame->l);
    auto cpp_right = mapper.map_right(frame->r);

    bool ok = true;
    ok &= compare_hand("L", cpp_left,  fix.at("left"));
    ok &= compare_hand("R", cpp_right, fix.at("right"));

    if (ok) {
        std::cout << "[INFO] all 24 joints within tolerance\n";
        return 0;
    }
    return 1;
}
